version: "3.8"

services:
  backend:
    build: ./backend
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8001:8001
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: mysql
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data:
